### ISSUE TITLE
DNSSEC test results

### ISSUE THREAD

**Issue by ghost** [kkebo/DNSecure#33]
Obtaining different DNSSEC test results (rootcanary.org) when using UncensoredDNS (@tykling) Unicast server:

* Manually configured server (DoH or DoT not enabled (screenshot A)
* DoH enabled through DNSecure app or installed profile @nitrohorse (screenshot DoH)
* DoT enabled through DNSecure app or installed profile @nitrohorse (screenshot DoT)

P.S. New DNS test page went live (beta) https://cmdns.dev.dns-oarc.net/
![A](https://user-images.githubusercontent.com/76554148/104119581-8d5ab600-5330-11eb-8bf9-c501b941b579.jpg)

![DoH](https://user-images.githubusercontent.com/76554148/104119584-95b2f100-5330-11eb-8ef1-3502df0b56bd.jpg)

![DoT](https://user-images.githubusercontent.com/76554148/104119589-9e0b2c00-5330-11eb-84c7-be5a7f4abc84.jpg)

**Comment by kkk669** [comment]
@zero0ID Is the URL used on your screenshots https://rootcanary.org/test.html?

What DNS provider do you use when you ran the tests?

My result was different from yours. (iPadOS 14.4 Beta 1, 1.1.1.1 (DoT))

![4912273D-1A32-4BC8-B7B1-1782EA9B151F](https://user-images.githubusercontent.com/601636/104189510-1d4a4e00-545e-11eb-9efa-766bb7cbc9f3.jpeg)

**Comment by zero0ID** [comment]
Hi,
the name of the server is in the first row:
"...using UncensoredDNS (@tykling <https://github.com/tykling>) Unicast server..."

https://blog.uncensoreddns.org/dns-servers/

-0ID
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


11 Jan 2021, 14:42 by notifications@github.com:
